//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LangGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LangGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILangGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] LangGrammarParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] LangGrammarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] LangGrammarParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.initialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitialization([NotNull] LangGrammarParser.InitializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] LangGrammarParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] LangGrammarParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_list([NotNull] LangGrammarParser.Expression_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.input_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput_statement([NotNull] LangGrammarParser.Input_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Output</c>
	/// labeled alternative in <see cref="LangGrammarParser.output_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput([NotNull] LangGrammarParser.OutputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.control_structure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControl_structure([NotNull] LangGrammarParser.Control_structureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] LangGrammarParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_statement([NotNull] LangGrammarParser.Switch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.case_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_clause([NotNull] LangGrammarParser.Case_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_loop([NotNull] LangGrammarParser.For_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_loop([NotNull] LangGrammarParser.While_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.do_while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDo_while_loop([NotNull] LangGrammarParser.Do_while_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] LangGrammarParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_definition([NotNull] LangGrammarParser.Function_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_list([NotNull] LangGrammarParser.Parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] LangGrammarParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_list([NotNull] LangGrammarParser.Argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] LangGrammarParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.pointer_manipulation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointer_manipulation([NotNull] LangGrammarParser.Pointer_manipulationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.struct_union_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_union_definition([NotNull] LangGrammarParser.Struct_union_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.struct_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_members([NotNull] LangGrammarParser.Struct_membersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LangGrammarParser.preprocessor_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreprocessor_directive([NotNull] LangGrammarParser.Preprocessor_directiveContext context);
}
