//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LangGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LangGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILangGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] LangGrammarParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] LangGrammarParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclude([NotNull] LangGrammarParser.IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclude([NotNull] LangGrammarParser.IncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainFunction([NotNull] LangGrammarParser.MainFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainFunction([NotNull] LangGrammarParser.MainFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LangGrammarParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LangGrammarParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] LangGrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] LangGrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] LangGrammarParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] LangGrammarParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] LangGrammarParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] LangGrammarParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] LangGrammarParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] LangGrammarParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] LangGrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] LangGrammarParser.ReturnStatementContext context);
}
