//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LangGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILangGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LangGrammarBaseListener : ILangGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrograma([NotNull] LangGrammarParser.ProgramaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrograma([NotNull] LangGrammarParser.ProgramaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.cabecalho"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCabecalho([NotNull] LangGrammarParser.CabecalhoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.cabecalho"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCabecalho([NotNull] LangGrammarParser.CabecalhoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.includeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludeDecl([NotNull] LangGrammarParser.IncludeDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.includeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludeDecl([NotNull] LangGrammarParser.IncludeDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.defineDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefineDecl([NotNull] LangGrammarParser.DefineDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.defineDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefineDecl([NotNull] LangGrammarParser.DefineDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.corpo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCorpo([NotNull] LangGrammarParser.CorpoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.corpo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCorpo([NotNull] LangGrammarParser.CorpoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.mainFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainFunction([NotNull] LangGrammarParser.MainFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.mainFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainFunction([NotNull] LangGrammarParser.MainFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloco([NotNull] LangGrammarParser.BlocoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloco([NotNull] LangGrammarParser.BlocoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.linhas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinhas([NotNull] LangGrammarParser.LinhasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.linhas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinhas([NotNull] LangGrammarParser.LinhasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.comentario"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComentario([NotNull] LangGrammarParser.ComentarioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.comentario"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComentario([NotNull] LangGrammarParser.ComentarioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtrib([NotNull] LangGrammarParser.AtribContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtrib([NotNull] LangGrammarParser.AtribContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.arrayDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDecl([NotNull] LangGrammarParser.ArrayDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.arrayDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDecl([NotNull] LangGrammarParser.ArrayDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.elementosArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementosArray([NotNull] LangGrammarParser.ElementosArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.elementosArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementosArray([NotNull] LangGrammarParser.ElementosArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.pointerDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointerDecl([NotNull] LangGrammarParser.PointerDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.pointerDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointerDecl([NotNull] LangGrammarParser.PointerDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.pointerAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointerAssign([NotNull] LangGrammarParser.PointerAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.pointerAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointerAssign([NotNull] LangGrammarParser.PointerAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.pointerDereference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointerDereference([NotNull] LangGrammarParser.PointerDereferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.pointerDereference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointerDereference([NotNull] LangGrammarParser.PointerDereferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.in"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIn([NotNull] LangGrammarParser.InContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.in"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIn([NotNull] LangGrammarParser.InContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput([NotNull] LangGrammarParser.OutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput([NotNull] LangGrammarParser.OutputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.getsStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetsStmt([NotNull] LangGrammarParser.GetsStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.getsStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetsStmt([NotNull] LangGrammarParser.GetsStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.putsStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPutsStmt([NotNull] LangGrammarParser.PutsStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.putsStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPutsStmt([NotNull] LangGrammarParser.PutsStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDecl([NotNull] LangGrammarParser.FunctionDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDecl([NotNull] LangGrammarParser.FunctionDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] LangGrammarParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] LangGrammarParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.parametros"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParametros([NotNull] LangGrammarParser.ParametrosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.parametros"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParametros([NotNull] LangGrammarParser.ParametrosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.argumentos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentos([NotNull] LangGrammarParser.ArgumentosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.argumentos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentos([NotNull] LangGrammarParser.ArgumentosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.structDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDecl([NotNull] LangGrammarParser.StructDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.structDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDecl([NotNull] LangGrammarParser.StructDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.structFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructFields([NotNull] LangGrammarParser.StructFieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.structFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructFields([NotNull] LangGrammarParser.StructFieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.unionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionDecl([NotNull] LangGrammarParser.UnionDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.unionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionDecl([NotNull] LangGrammarParser.UnionDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.unionFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionFields([NotNull] LangGrammarParser.UnionFieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.unionFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionFields([NotNull] LangGrammarParser.UnionFieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.structAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructAccess([NotNull] LangGrammarParser.StructAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.structAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructAccess([NotNull] LangGrammarParser.StructAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.unionAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionAccess([NotNull] LangGrammarParser.UnionAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.unionAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionAccess([NotNull] LangGrammarParser.UnionAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.decisionFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecisionFunc([NotNull] LangGrammarParser.DecisionFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.decisionFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecisionFunc([NotNull] LangGrammarParser.DecisionFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.switchCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchCase([NotNull] LangGrammarParser.SwitchCaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.switchCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchCase([NotNull] LangGrammarParser.SwitchCaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.caseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseBlock([NotNull] LangGrammarParser.CaseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.caseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseBlock([NotNull] LangGrammarParser.CaseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.defaultBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultBlock([NotNull] LangGrammarParser.DefaultBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.defaultBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultBlock([NotNull] LangGrammarParser.DefaultBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.loopFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopFunc([NotNull] LangGrammarParser.LoopFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.loopFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopFunc([NotNull] LangGrammarParser.LoopFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileLoop([NotNull] LangGrammarParser.WhileLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileLoop([NotNull] LangGrammarParser.WhileLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForLoop([NotNull] LangGrammarParser.ForLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForLoop([NotNull] LangGrammarParser.ForLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.doWhileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileLoop([NotNull] LangGrammarParser.DoWhileLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.doWhileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileLoop([NotNull] LangGrammarParser.DoWhileLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] LangGrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] LangGrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.terminais"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminais([NotNull] LangGrammarParser.TerminaisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.terminais"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminais([NotNull] LangGrammarParser.TerminaisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFator([NotNull] LangGrammarParser.FatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFator([NotNull] LangGrammarParser.FatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.exprbloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprbloco([NotNull] LangGrammarParser.ExprblocoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.exprbloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprbloco([NotNull] LangGrammarParser.ExprblocoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.casting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCasting([NotNull] LangGrammarParser.CastingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.casting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCasting([NotNull] LangGrammarParser.CastingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.typeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeof([NotNull] LangGrammarParser.TypeofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.typeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeof([NotNull] LangGrammarParser.TypeofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.ternary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTernary([NotNull] LangGrammarParser.TernaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.ternary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTernary([NotNull] LangGrammarParser.TernaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangGrammarParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] LangGrammarParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangGrammarParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] LangGrammarParser.ReturnStmtContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
